# Generated by Django 4.0.dev20210528085027 on 2021-06-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_alter_contacto_mail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
